version: '3.8'

services:
  jenkins:
    build: . # Builds using the Dockerfile in current directory
    container_name: jenkins
    ports:
      - "8080:8080"      # Jenkins UI port
      - "50000:50000"    # For Jenkins agent communication
    volumes:
      - jenkins_home:/var/jenkins_home  # Persist Jenkins configuration and job data
      - /var/run/docker.sock:/var/run/docker.sock  # Enables Docker within Jenkins if needed
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=true
    depends_on:
      - postgres

  postgres:
    image: postgres:14  # specify a version that fits your needs
    container_name: postgres
    ports:
      - "5433:5432" # Maps container's port 5432 to host's port 5433
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asdfghjkl;'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  jenkins_home:
  pgdata: