version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"      # Jenkins UI port
      - "50000:50000"    # For Jenkins agent communication
    volumes:
      - jenkins_home:/var/jenkins_home  # Persist Jenkins configuration and job data
      - /var/run/docker.sock:/var/run/docker.sock  # Enables Docker within Jenkins if needed
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

volumes:
  jenkins_home: